### ISSUE TITLE
[Task] 모든 my page 기능 구현

### ISSUE THREAD

**Issue by ciocio97** [codestates/Open-Spot#111]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: add functions to my page

### TODO
1. [x] 마이페이지 CSS 디테일하게 수정하기 (추후 리팩토링 고려)
2. [x] 마이페이지 이벤트 리스너 함수들 완성하고 연결하기
  -  회원 정보 페이지 (client / business)
  -  나의 보관함 페이지 (client / business)
  -  나의 가게함 페이지 (business)
  -  회원 정보 수정 모달창 (client / business)
  -  회원 탈퇴 요청 모달창 (client / business) 
3. [x] 만들어놓은 컴포넌트끼리 올바르게 연결하고 폴더 정리하기

### Estimated time
`12h`

### Labels
- Estimated time: `E: 12h`
- Group : `client`
- Sprint: `Sprint__NUMBER1`
- Urgency: `High`
