### ISSUE TITLE
[Task] 배포 후 Oauth 요청시 회원가입이 안 되거나 하는 여러 버그 픽스

### ISSUE THREAD

**Issue by jyang510** [codestates/Open-Spot#126]
### ISSUE
- Group:   `server`
- Type: `feature`
- Detail: fix Oauth Login bug

### TODO
1. [x] 구글 Oauth 로그인 시 쿠키와 200 상태 코드 출력해주기
2. [x] 카카오 Oauth 로그인 시 쿠키와 200 상태 코드 출력해주기
3. [ ] 네이버 Oauth 로그인 시 쿠키와 200 상태 코드 출력해주기

### Labels
- Estimated time: `E: 2.5h`
- Group : `client`, `server`
- Sprint: `Sprint__1`
- Urgency:  `Low`
