### ISSUE TITLE
[Task] 클라이언트 로그인 버그 수정

### ISSUE THREAD

**Issue by ciocio97** [codestates/Open-Spot#130]
### ISSUE
- Group:  `client`
- Type: `bug`, `feature`
- Detail: fix social login bug, add oauthLogin, link map page router 

### TODO
1. [X] 로그인 상태에 oauthLogin 키 추가
2. [X] map 페이지 라우터 연결
3. [X] 소셜 로그인 버그 수정

### Labels
- Estimated time: `E: 2h`
- Group : `client`
- Sprint: `Sprint__NUMBER1`
- Urgency: `Middle`
