### ISSUE TITLE
[Task] 홈페이지 메인 화면 구현

### ISSUE THREAD

**Issue by ciocio97** [codestates/Open-Spot#17]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 홈페이지의 첫 화면, 메인 페이지 구현

### TODO
1. [ ] 모든 페이지의 헤더에 고정될 프로젝트 아이콘 디자인 + 홈 리다이렉션 링크 연결
2. [ ] Scroll Down 클릭 시 아래 섹션으로 넘어가는 애니메이션 구현
3. [ ] 지도 Tab, 로그인 Tab, 회원가입 Tab, 지도 체험 버튼 구현

### Labels
- Estimated time: `E: 1.5h`
- Group : `client`
- Sprint: `Sprint__1`
- Urgency: `Middle`
