### ISSUE TITLE
[Task] 홈페이지 메인화면 구현

### ISSUE THREAD

**Issue by ciocio97** [codestates/Open-Spot#18]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 홈페이지의 첫 화면, 메인 페이지 구현

### TODO
1. [x] 모든 페이지의 헤더 부분에 고정될 project logo 디자인 (+홈 페이지 리다이렉션 기능)
2. [x] Scroll Down 버튼 클릭 시 다음 섹션(서비스 소개 섹션)으로 내려가는 애니메이션 추가
3. [x] 지도 Tab, 로그인 Tab, 회원가입 Tab, 지도 체험 버튼 구현

### Labels
- Estimated time: `E: 2h`
- Group : `client`
- Sprint: `Sprint__1`
- Urgency: `Middle`
