### ISSUE TITLE
[Task] business 회원가입 페이지 구현

### ISSUE THREAD

**Issue by ciocio97** [codestates/Open-Spot#26]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 사업자 회원을 위한 회원가입 페이지 구현

### TODO
1. [x] 닉네임, 이메일, 비밀번호 유효성 검사
2. [x] 유효성 검사에 따른 결과 (통과/불통과) 꼭 알려주기
3. [x] 사업자 등록 번호 API 인증 연결 `Advanced`

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 5h`
- Group : `client`
- Sprint: `Sprint__1`
- Urgency: `High`
