### ISSUE TITLE
[Task] client & business 마이페이지 / 회원 탈퇴 모달창 구현

### ISSUE THREAD

**Issue by Brian-free1** [codestates/Open-Spot#27]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: - 사용자가 회원 탈퇴 하는 기능

### TODO
1. [x] 회원 탈퇴 클릭 시 회원 탈퇴 모달창을 띄운다.
2. [x] 탈퇴 사유는 관리자 메일로 해당 사용자 정보와 함께 같이 전달된다 `Advanced`
3. [x] 비밀번호 일치하지 않을 시 '비밀 번호가 일치하지 않습니다.' 라는 메세지 창을 띄운다.
4. [x] 탈퇴 완료 버튼 클릭 시 로그인 되지 않은 홈페이지가 나온다.

### Labels
- Estimated time: `E: 2.5h`
- Group : `client`
- Sprint: `Sprint__1`
- Urgency: `Middle`
