### ISSUE TITLE
[Task] client 마이페이지 헤더 구현

### ISSUE THREAD

**Issue by Brian-free1** [codestates/Open-Spot#29]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 개인 마이페이지 헤더 구현

### TODO
1. [x] 로고 이미지 버튼 -> 홈페이지로 가게 되는 이벤트 ( 소비자로 로그인된 상태 )
2. [x] Map Tab -> Map 페이지로 가게되는 이벤트 ( 소비자로 로그인된 상태 )
3. [x] LOGOUT Tab -> 홈페이지로 가게되는 이벤트 ( 로그인 되지 않은 상태 )
4. [x] My Page Tap -> My Page로 가게되는 이벤트 ( 소비자로 로그인된 상태 )
5. [x] Background Img 구현

### Labels
- Estimated time: `E: 1h`
- Group : `client`
- Sprint: `Sprint__1`
- Urgency: `Low`
