### ISSUE TITLE
[Task] business 마이 페이지 헤더 구현

### ISSUE THREAD

**Issue by Brian-free1** [codestates/Open-Spot#30]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 사업자 마이페지 헤더 구현

### TODO
1. [x] 로고 이미지 버튼 -> 홈페이지로 가게 되는 이벤트 ( 사업자로 로그인된 상태 )
2. [x] Map 이미지 버튼 -> Map 페이지로 가게되는 이벤트 ( 사업자로 로그인된 상태 )
3. [x] LOGOUT 이미지 버튼 -> 홈페이지로 가게되는 이벤트 ( 로그인 되지 않은 상태로 )
4. [x] My Page Tap -> My Page로 가게되는 이벤트 ( 사업자로 로그인된 상태 )
5. [x] Background Img 구현

### Labels
- Estimated time: `E: 2h`
- Group : `client`
- Sprint: `Sprint__1`
- Urgency: `Low`
