### ISSUE TITLE
[Task] 사전 준비

### ISSUE THREAD

**Issue by Brian-free1** [codestates/Open-Spot#34]
### ISSUE
- Group:  `sr`
- Type:`feature`
- Detail: 기획 To Do 리스트

### TODO
1. [ ] 팀장 선정, 팀 이름, 프로젝트 이름
2. [ ] 위키에 들어가야 할 내용
3. [ ] 프로젝트 아이디에이션
4. [ ] 팀 규칙 작성
5. [ ] 팀원별 역할 설정 (포지션 분배)

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 3h`
- Group : `client`, `server`
- Sprint: `SR 기획`
- Urgency: `Low`
