### ISSUE TITLE
[Task] 프로젝트 기획 및 범위 설정

### ISSUE THREAD

**Issue by Brian-free1** [codestates/Open-Spot#35]
### ISSUE
- Group:  `sr`
- Type:`feature`
- Detail: 프로젝트 기획 및 범위 설정
### TODO
1. [ ] 프로젝트 기획 및 범위 설정
2. [ ] Bare Minimum 항목이 기능 To Do 리스트 중 필수 항목을 포함하는지 확인하고 만들기
3. [ ] Bare Minimum 기능에 대해 구현 가능성을 늘 염두하기

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 0.5h`
- Group : `client`, `server`
- Sprint: `SR 기획`
- Urgency: `Low`
