### ISSUE TITLE
[Task] 위키 및 기능 To Do 리스트 작성

### ISSUE THREAD

**Issue by Brian-free1** [codestates/Open-Spot#38]
### ISSUE
- Group:  `sr`
- Type:`feature`
- Detail: 위키 및 기능 To Do 리스트 작성

### TODO
1. [ ] 위키 작성
2. [ ] 기능 To Do 리스트 작성
3. [ ] 필수 및 권장 항목을 먼저 체크합니다.
4. [ ] 아이디어와 구현 범위를 바탕으로 시스템 아키텍처 및 UI/UX의 각 항목과의 연관성을 파악합니다.
5. [ ] Advanced (도전) 또는, Nightmare (신중) 항목에 대해서 연구할 수 있는 충분한 자원이 있는지 파악하고 작성한다.
6. [ ] To Do 리스트를 통해 태스크 카드 작성을 보다 쉽게 해본다.

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 3h`
- Group : `client`, `server`
- Sprint: `SR 기획`
- Urgency: `High`
