### ISSUE TITLE
[Task] business 마이 페이지 / 나의 가게 등록하기 모달창

### ISSUE THREAD

**Issue by Brian-free1** [codestates/Open-Spot#42]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 가게 등록하기 모달창 구현

### TODO
1. [x] 가게 등록하기 버튼 클릭 시 모달창이 나온다.
2. [x] 사업자 등록 번호 API 인증 연결 `Advanced`
3. [x] 인증 완료, 정보 입력 후 나의 가게 정보함에 새로 등록한 가게 정보가 리스트 업 된다. `Advanced`
4. [x] 동시에 등록한 정보를 토대로 새로운 마커가 지도에 생성된다. `Advanced`

### Labels
- Estimated time: `E: 5h`
- Group : `client`
- Sprint: `Sprint__1`
- Urgency: `High`
