### ISSUE TITLE
[Task] business 마이 페이지 구현

### ISSUE THREAD

**Issue by Brian-free1** [codestates/Open-Spot#44]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: business 마이 페이지 첫 화면 구현

### TODO
1. [x] 헤더 구현하기
2. [x] side bar 구현하기
3. [x] side bar 안에 각각의 페이지로 연결되는 버튼 구현( 기능 구현 X )
4. [x] 첫 화면은 회원 정보 페이지가 나타나야 한다.

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint__1`
- Urgency: `Low`
