### ISSUE TITLE
[Task] guest & client & business Map 페이지 구현

### ISSUE THREAD

**Issue by Brian-free1** [codestates/Open-Spot#45]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: Map 페이지 구현

### TODO
1. [ ] 지도 API 가져오기
2. [ ] 화면 전체에 지도 이미지 구현
3. [ ] menu 이미지 구현
4. [ ] 지도 위에 핀 나오게 구현 ( 가게 주소와 일치하게 있어야 함 )

### Labels
- Estimated time: `E: 5h`
- Group : `client`
- Sprint: `Sprint__1`
- Urgency: `High`
