### ISSUE TITLE
[Task] client & business menu 모달창 구현 

### ISSUE THREAD

**Issue by Brian-free1** [codestates/Open-Spot#47]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: menu 모달창 구현 

### TODO
1. [x] 로고 이미지 구현
2. [x] 로고 이미지 클릭 시 홈페이지 이동 ( 사업자 or 개인 로그인 상태 )
3. [x] My page 이동 버튼 구현
4. [x] My page 이동 버튼 클릭 시 my page로 이동 ( 사업자 or 개인 로그인 상태 )
5. [x] 'X' 표시 이미지 구현 -> 클릭 시 모달창 숨김

### Labels
- Estimated time: `E: 5h`
- Group : `client`
- Sprint: `Sprint__1`
- Urgency: `Middle`
