### ISSUE TITLE
[Task] guest menu 모달창 구현

### ISSUE THREAD

**Issue by Brian-free1** [codestates/Open-Spot#49]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: guest menu 모달창 구현

### TODO
1. [x] menu 이미지 클릭 시 모달창을 띄운다.
2. [x] 로고 이미지 구현
3. [x] 로고 이미지 클릭 시 홈 페이지 이동 ( guest 상태 유지 )
4. [x] 'X' 이미지 구현
5. [x] 'X' 이미지 클릭 시 모달창 숨김

### Labels
- Estimated time: `E: 1h`
- Group : `client`
- Sprint: `Sprint__1`
- Urgency: `Low`
