### ISSUE TITLE
[Task] guest 핀 모달창 구현

### ISSUE THREAD

**Issue by Brian-free1** [codestates/Open-Spot#50]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 핀 모달창 구현

### TODO
1. [x] 핀 클릭 시 모달창이 나온다
2. [x] 로고 이미지 구현
3. [x] 로고 이미지 클릭 시 홈 페이지 이동 ( guest 상태 유지 )
4. [x] 'X' 이미지 구현
5. [x]  'X' 이미지 클릭 시 모달창 숨김
6. [x] 내 목록에 담기 버튼 구현
7. [x] 내 목록에 담기 버튼 클릭 시 로그인 페이지 이동

### Labels
- Estimated time: `E: 2h`
- Group : `client`
- Sprint: `Sprint__1`
- Urgency: `Low`
