### ISSUE TITLE
[Task] 나의 보관함 / 사업자 보관함 마커 조회 구현

### ISSUE THREAD

**Issue by jyang510** [codestates/Open-Spot#7]
### ISSUE
- Group:  `server`
- Type: `feature`
- Detail: 마이페이지에서 나의 보관함, 사업자 보관함 마커 조회 구현

### TODO
1. [x] 유저의 토큰을 이용해, 해당 유저 아이디가 저장한 마커들을 조회하는 기능 구현
2. [x] /users/general-markers 로 보관함의 마커들을 가져온다.
3. [x] /users/business-markers 로 가게함의 마커들을 가져온다.

### Labels
- Estimated time: `E: 4h`
- Group :  `server`
- Sprint: `Sprint__1`
- Urgency: `Middle`
